version: "3.7"

services:
  app:
    build:
      context: .
    image: excypher-dev:latest
    volumes:
      - $PWD:/excypher
    working_dir: /excypher
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:3.5
    environment:
      NEO4J_AUTH: none
