#!/bin/bash

command_name=$1
shift
command_args=$@

image_name="ex-cypher"

case $command_name in
  build)
    echo "Building dev environment...."
    docker-compose build --build-arg uid=$EUID
  ;;

  bash)
    docker-compose run --rm app ./script/wait_for_neo4j bash
  ;;
esac
