#!/bin/bash

set -e

cmd="$@"

check_server_availability() {
  url=$1

  until curl -i "http://$url:7474" 2>&1 | grep -c -e '200 OK'; do
    echo "Waiting for neo4j at $url..."
    sleep 1
  done
}

check_server_availability "neo4j"

echo "All servers up!"
exec $cmd
