name: Code Quality

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code Quality
    needs: Test

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4
        otp-version: 22.2

    - name: Install Dependencies
      run: mix deps.get
    - name: Mix format
      run: mix format --check-formatted
    - name: Mix Credo
      run: mix credo --strict
