name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [22.2]
        elixir: [1.9.4]

    services:
      neo4j:
        image: neo4j:3.5
        env:
          NEO4J_AUTH: none
        ports:
          - 7474:7474
          - 7687:7687

    env:
      NEO4J_HOST: localhost
      NEO4J_HTTP_PORT: 7474
      NEO4J_PORT: 7687


    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}

    - name: Install Dependencies
      run: mix deps.get
    - name: Wait neo4j server to be available...
      run: ./script/wait_for_neo4j
    - name: Compile
      run: MIX_ENV=test mix compile
    - name: Run Tests
      run: mix coveralls

  quality:
    runs-on: ubuntu-latest
    name: Code Quality
    needs: test

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4
        otp-version: 22.2

    - name: Install Dependencies
      run: mix deps.get
    - name: Mix format
      run: mix format --check-formatted
    - name: Mix Credo
      run: mix credo --strict
