name: Mix Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.2]
        elixir: [1.8.2, 1.9.4]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}

    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
