name: Test (elixir 1.7.4)

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.7.4-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
